// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcLLfpC9QQG0zLYd6yylp2SEagFLeJdJ0',
    appId: '1:241891833656:web:f563eb8f2d5fde15b573cd',
    messagingSenderId: '241891833656',
    projectId: 'tubes-b25a6',
    authDomain: 'tubes-b25a6.firebaseapp.com',
    storageBucket: 'tubes-b25a6.firebasestorage.app',
    measurementId: 'G-GFTZ96B8KK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8VgI5E6bBtAJs2KInrMXwXdSAlDmB40s',
    appId: '1:241891833656:android:a3c08983bce08d61b573cd',
    messagingSenderId: '241891833656',
    projectId: 'tubes-b25a6',
    storageBucket: 'tubes-b25a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_CattFgSe_7xPrta9fvxxu3329FmRxNg',
    appId: '1:241891833656:ios:07991be9313958beb573cd',
    messagingSenderId: '241891833656',
    projectId: 'tubes-b25a6',
    storageBucket: 'tubes-b25a6.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiCafe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_CattFgSe_7xPrta9fvxxu3329FmRxNg',
    appId: '1:241891833656:ios:07991be9313958beb573cd',
    messagingSenderId: '241891833656',
    projectId: 'tubes-b25a6',
    storageBucket: 'tubes-b25a6.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiCafe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcLLfpC9QQG0zLYd6yylp2SEagFLeJdJ0',
    appId: '1:241891833656:web:1fe866f1b58be47ab573cd',
    messagingSenderId: '241891833656',
    projectId: 'tubes-b25a6',
    authDomain: 'tubes-b25a6.firebaseapp.com',
    storageBucket: 'tubes-b25a6.firebasestorage.app',
    measurementId: 'G-96502C9DGR',
  );
}
